services:
  - type: web
    name: school-id
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y chromium
      pip install -r requirements.txt
    startCommand: gunicorn app:app